sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  - go vet -v ./...
  - go test -race -v ./... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

-after_success:
  - coveralls